spring.application.name=user-service
server.servlet.context-path=/api/user
server.port=8082

spring.profiles.active=local

# Local PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-sparkling-mouse-ayji4291-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_NGeLjF2YWKt1
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Local Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=YuktiSetu@2026
spring.data.redis.timeout=2000ms

yuktisetu.jwt.public-key-path=classpath:/keys/public.pem
yuktisetu.jwt.issuer=auth-service
